spring.application.name=payment-processor

# --- Oracle ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=Password123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# --- ActiveMQ ---
camel.component.activemq.broker-url=tcp://localhost:61616
camel.component.activemq.username=admin
camel.component.activemq.password=admin

# --- Camel ---
camel.springboot.main-run-controller=true